/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itenas.javabakery.view.swing;

import com.itenas.javabakery.pojo.Akun;
import com.itenas.javabakery.pojo.Keranjang;
import com.itenas.javabakery.pojo.Member;
import com.itenas.javabakery.pojo.Produk;
import com.itenas.javabakery.service.KeranjangService;
import com.itenas.javabakery.service.ProdukService;
import com.itenas.javabakery.serviceimpl.KeranjangServiceImpl;
import com.itenas.javabakery.serviceimpl.ProdukServiceImpl;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class Homepage extends javax.swing.JFrame {
    
    /**
     * Creates new form Homepage
     */
    Akun akun;
    ProdukService produkService;
    KeranjangService keranjangService;
    String usrname;
    
    public Homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadData();
        
    }
    
    public Akun getAkunInfo(Akun akn) {
        akun = akn;
        
        //lblNamaUser.setText(akun.getAkun().getNama());
        lblUsername.setText(akun.getAkun().getUsername());
        usrname = lblUsername.getText();
//        testUsername.setText(lblUsername.getText());
        
        return akun;
    }
    
    /*public String getAkunInfo(String username) {
        lblUsername.setText(username);
//        lblUsername.setText(akun.getAkun().getUsername());
        
        usrname = lblUsername.getText();
        testUsername.setText(lblUsername.getText());
        
        return username;
    }*/
    
    public void close() {
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    
        private void emptyField() {
            lblIDProduk.setText("");
            txtNamaProduk.setText("");
            txtHarga.setText("");
            //lblImage.setIcon(null);
    }
    
    private void loadData() {
        produkService = new ProdukServiceImpl();
        List<Produk> listProduk;
        sort = comboSortir.getSelectedItem().toString();
        
        if (sort.equals("Nama")){
            listProduk = produkService.sortByCondition3();
        } else if (sort.equals("Harga")){
            listProduk = produkService.sortByCondition4();
        } else {
            listProduk = produkService.findAllTersedia();
        }
        Object[][] objectProduk = new Object[listProduk.size()][6];
        
        int counter = 0;
        
        for (Produk produk : listProduk) {
            if (produk.getStatus().equals("Tersedia")){
                objectProduk[counter][0] = produk.getId();
                objectProduk[counter][1] = produk.getNama();
                objectProduk[counter][2] = produk.getHarga();
                objectProduk[counter][3] = produk.getImage();
            }
            counter++;
        }
        
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            objectProduk,
            new String [] {
                "ID Produk", "Nama Produk", "Harga", "Image"
            }
        ));
    }
    
    private void loadData(Produk produk) {
        Object[][] objectProduk = new Object[1][6];
        
        if (produk.getStatus().equals("Tersedia")){
            objectProduk[0][0] = produk.getId();
            objectProduk[0][1] = produk.getNama();
            objectProduk[0][2] = produk.getHarga();
            objectProduk[0][3] = produk.getImage();
        }
            
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            objectProduk,
            new String [] {
                "ID Produk", "Nama Produk", "Harga", "Image"
            }
        ));
    }
    
    private Produk findProduk(String name) {
        Produk produk = new Produk();
        produkService = new ProdukServiceImpl();
        produk = produkService.findByNama(name);
    
        return produk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAddToCart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblIDProduk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        lblImage2 = new javax.swing.JLabel();
        txtCariNama = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        comboSortir = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        lblY = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 50, 73));

        btnHome.setBackground(new java.awt.Color(0, 50, 73));
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\home-icon-silhouette (1).png")); // NOI18N
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);

        btnCart.setBackground(new java.awt.Color(255, 255, 255));
        btnCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\shopping-cart.png")); // NOI18N
        btnCart.setBorder(null);
        btnCart.setBorderPainted(false);
        btnCart.setContentAreaFilled(false);
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        btnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\logout.png")); // NOI18N
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnProfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\user.png")); // NOI18N
        btnProfil.setBorder(null);
        btnProfil.setBorderPainted(false);
        btnProfil.setContentAreaFilled(false);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(43, 43, 43)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setText("username :");

        lblUsername.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblUsername.setText("x");

        tblProduk.setAutoCreateRowSorter(true);
        tblProduk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama", "Harga", "Image"
            }
        ));
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        btnAddToCart.setBackground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\add-to-cart.png")); // NOI18N
        btnAddToCart.setText("Tambah ke Keranjang");
        btnAddToCart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAddToCart.setBorderPainted(false);
        btnAddToCart.setContentAreaFilled(false);
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 20)); // NOI18N
        jLabel1.setText("DETAIL PRODUK");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        jLabel6.setText("ID Produk");

        lblIDProduk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        lblIDProduk.setText("x");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setText("Nama Produk");

        txtNamaProduk.setEditable(false);
        txtNamaProduk.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaProduk.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        txtNamaProduk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 50, 73)));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setText("Harga Produk");

        txtHarga.setEditable(false);
        txtHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtHarga.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        txtHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 50, 73)));

        jDesktopPane4.setBorder(new javax.swing.border.MatteBorder(null));

        jDesktopPane4.setLayer(lblImage2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
        );

        txtCariNama.setBackground(new java.awt.Color(244, 237, 252));
        txtCariNama.setText("Cari melalui nama..");
        txtCariNama.setBorder(null);
        txtCariNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariNamaMouseClicked(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCari.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\Bahan\\Zoom-icon.png")); // NOI18N
        btnCari.setBorder(null);
        btnCari.setBorderPainted(false);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        comboSortir.setBackground(new java.awt.Color(204, 204, 204));
        comboSortir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        comboSortir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortir", "Nama", "Harga" }));
        comboSortir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSortirItemStateChanged(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Downloads\\refresh-page-option.png")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblY.setText("y");

        lblB.setText("b");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUsername)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIDProduk))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(txtHarga)
                                .addComponent(txtNamaProduk)
                                .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblY)
                                .addGap(18, 18, 18)
                                .addComponent(lblB)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblIDProduk))
                        .addGap(7, 7, 7)
                        .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblY)
                            .addComponent(lblB))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblUsername)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboSortir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        
        LoginForm lf = new LoginForm();
        dispose();
        lf.setVisible(true);
        
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        
        KeranjangManagement km = new KeranjangManagement();
        //km.getAkunInfo(usrname);
        km.getAkunInfo(akun);
        km.loadData(akun);
        km.Refresh(akun);
        //km.getAkunInfo();
        dispose();
        km.setVisible(true);
    }//GEN-LAST:event_btnCartActionPerformed

    private void txtCariNamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariNamaMouseClicked
        // TODO add your handling code here:
        
        txtCariNama.setText("");
    }//GEN-LAST:event_txtCariNamaMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:

        String nama;
        Produk searchedProduk = new Produk();

        nama = txtCariNama.getText().toString();
        searchedProduk = findProduk(nama);
        if (searchedProduk != null) {
            loadData(searchedProduk);
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void comboSortirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSortirItemStateChanged
        // TODO add your handling code here:

        sort = comboSortir.getSelectedItem().toString();

        if (sort.equals("Tersedia")){
            produkService.sortByCondition1();
        } else if (sort.equals("Tidak Tersedia")){
            produkService.sortByCondition2();
        }
    }//GEN-LAST:event_comboSortirItemStateChanged

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        
        String namaProduk, image;
        int idProduk;
        double harga;
        //keranjangService = new KeranjangServiceImpl();
        produkService = new ProdukServiceImpl();
        
        idProduk = Integer.parseInt(lblIDProduk.getText());
        String tempRef = String.valueOf(idProduk);
        namaProduk = txtNamaProduk.getText();
        harga = Double.parseDouble(txtHarga.getText());
        
        Produk produk = new Produk();
        produk.setId(idProduk);
        produk.setNama(namaProduk);
        produk.setHarga(harga);
        produk.setImage(produkImage);
        
        //Keranjang keranjang = new Keranjang();
        //keranjang.setIdproduk(idProduk);
        
        keranjangService = new KeranjangServiceImpl();
        List<Keranjang> listKeranjang;

        listKeranjang = keranjangService.findProductID(lblUsername.getText());
        Object[][] objectKeranjang = new Object[listKeranjang.size()][3];
        
        int counter = 0;
        
        for (Keranjang keranjang : listKeranjang) {
            objectKeranjang[counter][0] = keranjang.getIdproduk();
            String tempId = String.valueOf(objectKeranjang[counter][0]);
            
            if (tempRef.equals(tempId)){
                produkService.addAvailableProduct(lblUsername.getText(), produk);
                lblY.setText(tempRef);
                lblB.setText(tempId);
            } else {
                produkService.addProduct(lblUsername.getText(), produk);
                lblY.setText(tempRef);
                lblB.setText(tempId);
            }
            counter++;
        }
        
        //keranjangService.addProduct(lblUsername.getText(), keranjang);
        JOptionPane.showMessageDialog(null, "Produk telah ditambahkan ke Keranjang!");
        loadData();
        emptyField();
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        // TODO add your handling code here:
        
        String namaProduk, image;
        int idProduk;
        double harga;
        
        int row = tblProduk.getSelectedRow();
        idProduk = Integer.parseInt(tblProduk.getValueAt(row, 0).toString());
        namaProduk = tblProduk.getValueAt(row, 1).toString();
        harga = Double.parseDouble(tblProduk.getValueAt(row, 2).toString());
        image = tblProduk.getValueAt(row, 3).toString();
        
        lblIDProduk.setText(idProduk+"");
        txtNamaProduk.setText(namaProduk);
        txtHarga.setText(harga+"");
        //lblImage.setIcon(produkIcon);
    }//GEN-LAST:event_tblProdukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> comboSortir;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblIDProduk;
    private javax.swing.JLabel lblImage2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblY;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtCariNama;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNamaProduk;
    // End of variables declaration//GEN-END:variables
    private String sort;
    String namaFileProduk = null;
    private ImageIcon produkIcon = null;
    byte[] produkImage = null;
}
